### ISSUE TITLE
Project not centered in voxelization even centered in CAD

### ISSUE THREAD

**Issue by xsun-23** [computed-axial-lithography/VAMToolbox#4]
I have had problem with the object not being at the center of the rotational axis in voxelization even though it is centered in my CAD. In that case, you can rotate your STL file around the z axis (the rotational axis for optimization) for 180 degrees, and it would be solved

**Comment by stisa** [comment]
Hi, could you provide an example stl file and python script that show this behaviour?

**Comment by xsun-23** [comment]
[20mm cube v1.zip](https://github.com/computed-axial-lithography/VAMToolbox/files/9600667/20mm.cube.v1.zip)
hi this file is an example 

this is the python line i used to voxelize this:
target_geo = vam.geometry.TargetGeometry(stlfilename=r"C:\Users\taylo\Documents\members\X Sun\pixels optimization\20mm cube v1.STL", resolution=1)

**Comment by xsun-23** [comment]
Seems like when I use a very small resolution, the grid for voxelization is actually smaller than the object itself

**Comment by xsun-23** [comment]
Also this file, resolution used is 177 but seems to not be recongnized as centered by the algorithm
[New folder.zip](https://github.com/computed-axial-lithography/VAMToolbox/files/9691485/New.folder.zip)

**Comment by jttoombs** [comment]
This issue has been fixed with a new voxelizer with better stability and handling of mesh positions. Please open a new issue if the problem persists with the new version.
